/**
 * Apply migrations, then exit.
 *
 * Migrations are plain SQL under db/migrations, generated by `pnpm db:generate`
 * and readable in review. The controller does not migrate on boot: a schema
 * change is a deliberate step, not a side effect of one replica winning a race
 * with another during a deploy.
 */
import { getConfig } from "../config";
import { createDatabase } from "./client";
import { migrateDatabase } from "./migrate-runner";

await migrateDatabase(createDatabase(getConfig().databaseUrl));

process.stdout.write("migrations applied\n");
process.exit(0);
