/**
 * File-size check.
 *
 * A file that has grown past a few hundred lines is usually two files that
 * have not been split yet, and every reader pays for that: a human in review,
 * an agent loading it into context. The fix is almost always "find the second
 * responsibility and move it", which is cheap early and painful late.
 *
 * Only source files are checked. Generated or append-only files are exempt:
 * migrations are written by drizzle-kit, lockfiles by pnpm, and prose is not
 * code.
 *
 * Run: pnpm files:check
 */
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

/** Past this many lines a source file fails the check. */
const MAX_LINES = 500;

const SKIP_DIRS = new Set([
  "node_modules",
  ".git",
  ".next",
  ".turbo",
  "dist",
  ".specstory",
  ".codegraph",
  // Third-party code kept for reference; not ours to police.
  "references",
  // Generated by drizzle-kit from db/schema.ts; size tracks the schema.
  "migrations",
]);

const SOURCE_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);

function sourceFiles(dir: string): string[] {
  const found: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith(".") && entry.name !== ".github") continue;
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (!SKIP_DIRS.has(entry.name)) found.push(...sourceFiles(path));
      continue;
    }
    const dot = entry.name.lastIndexOf(".");
    if (dot > 0 && SOURCE_EXTENSIONS.has(entry.name.slice(dot))) found.push(path);
  }
  return found;
}

const violations = sourceFiles(".").flatMap((file) => {
  // readFileSync on a source file we just listed; statSync keeps the type
  // honest (a broken symlink would otherwise throw a confusing error).
  if (!statSync(file).isFile()) return [];
  const lines = readFileSync(file, "utf8").split("\n").length - 1;
  return lines > MAX_LINES ? [{ file, lines }] : [];
});

if (violations.length > 0) {
  console.error(`Source files over ${MAX_LINES} lines:\n`);
  for (const { file, lines } of violations) {
    console.error(`  ${file}: ${lines} lines`);
  }
  console.error("\nSplit the second responsibility out into its own file.");
  process.exit(1);
}

process.stdout.write(`File sizes OK (all source files within ${MAX_LINES} lines)\n`);
