# This is a config for E2B sandbox template.
# You can use template ID (7fgnza6amhmt4hnsild0) or template name (coreview-agent) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("coreview-agent") # Sync sandbox
# sandbox = await AsyncSandbox.create("coreview-agent") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('coreview-agent')

team_id = "f7d8c71b-1bc4-445c-a9dd-427bab858ee4"
memory_mb = 4_096
cpu_count = 4
start_cmd = "sleep infinity"
dockerfile = "Dockerfile.sandbox"
template_name = "coreview-agent"
template_id = "7fgnza6amhmt4hnsild0"
